export class Business {
    constructor(
        public id?: string,
        public entityName?: string,
        public entityType?: string,
        public dba?: string,
        public MCMXFFNumbers?: string,
        public streetNumber?: string,
        public streetName?: string,
        public city?: string,
        public state?: string,
        public zipCode?: string,
        public fullAddress?: string,
        public usDotNumber?: string,
        public numberOfTractors?: string,
        public numberOfTrailers?: string,
        public listOfTractors?: string,
        public listOfTrailers?: string,
        public numberOfDrivers?: string,
        public listOfDrivers?: string,
        public cargo?: string,
        public cargoLimit?: string,
        public autoLiabilityLimits?: string,
        public hasLiabilityClaims?: string,
        public website?: string,
        public businessType?: string,
        public businessStartMonth?: string,
        public businessStartYear?: string,
        public yearsInBusiness?: string,
        public numberOfEmployees?: string,
        public industry?: string,
        public hasHadCyberAttack?: string,
        public revenue?: string,
        public hasSoftwareBusiness?: string,
        public numberOfProtectedRecords?: string,
        public hasCryptoCurrencyBusiness?: string,
        public hasAntiVirus?: string,
        public hasHippaCompliance?: string,
        public cyberLimit?: string,
        public streetAddress?: string,
        public clientBusinessId?: number,
        public companyBusinessId?: number
    ){}
}
