import { Client } from "./client.model";
import { Vehicle } from "./vehicle.model";
import { Incident } from "./incident.model";

export class Driver {
  constructor(
    public id?: string,
    public contractEffectiveDt?: Date,
    public contractExpDt?: Date,
    public otherPolicyCd?: string,
    public otherPolicyName?: string,
    public otherPolicyLobCd?: string,
    public otherPolicyExpDt?: Date,
    public applicantSurname?: string,
    public applicantGivenName?: string,
    public applicantMiddleInitial?: string,
    public applicantNameSuffix?: string,
    public applicantCommUsedCd?: string,
    public applicantCommPhoneNumber?: string,
    public applicantCommEmailAddress?: string,
    public applicantGenderCd?: string,
    public applicantBirthDt?: Date,
    public applicantMaritalStatusCd?: string,
    public applicantOccupationClassCd?: string,
    public applicantPreviousInsurance?: string,
    public applicantPreviousInsuranceYears?: string,
    public applicantPreviousInsuranceMonths?: string,
    public driverLicensedDt?: string,
    public driverLicenseNumber?: string,
    public driverLicenseStateCd?: string,
    public driverScore?: number,
    public ownOrRent?: string,
    public currentlyInsured?: boolean,
    public creditScore?: string,
    public priorPenalties?: string,
    public priorPenaltiesText?: string,
    public priorClient?: boolean,
    public hasCancelled?: boolean,
    public sfInsuredId?: string,
    public hasHomeBundle?: boolean,
    public hasRentersBundle?: boolean,
    public hasHomeownersDiscount?: boolean,
    public hasMilitaryDiscount?: boolean,
    public hasPayInFullDiscount?: boolean,
    public hasAutoPayDiscount?: boolean,
    public hasDefensiveDriverDiscount?: boolean,
    public hasGoodStudentDiscount?: boolean,
    public hasRideshare?: boolean,
    public daysLapseInCoverage?: string,
    public age?: number,
    public drivingExperience?: number,
    public preferredContactMethod?: string,
    public educationLevel?: string,
    public relationship?: string,
    public needsSR22?: boolean,
    public hasCommercialBundle?: boolean,
    public hasLifeBundle?: boolean,
    public streetNumber?: string,
    public streetName?: string,
    public city?: string,
    public state?: string,
    public zipCode?: string,
    public fullAddress?: string,
    public unitNumber?: string,
    public fullName?: string,
    public client?: Client,
    public vehicles?: Vehicle[],
    public incidents?: Incident[],
    public clientDriverId?: number,
    public companyDriverId?: number,
    public vehicleId?: number
 ) {}
}
